services:
  ocr_rag_ui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8502:8502"
    container_name: ocr_rag_ui
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ocr_rag_ui.rule=Host(`yourdomain.com`)"
      - "traefik.http.routers.ocr_rag_ui.entrypoints=websecure"
      - "traefik.http.routers.ocr_rag_ui.tls=true"
      - "traefik.http.services.ocr_rag_ui.loadbalancer.server.port=8502"
      - "traefik.http.services.ocr_rag_ui.loadbalancer.healthcheck.path=/healthz"
      - "traefik.http.services.ocr_rag_ui.loadbalancer.healthcheck.interval=30s"
      - "traefik.http.services.ocr_rag_ui.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.services.ocr_rag_ui.loadbalancer.healthcheck.scheme=http"
